language: node_js
node_js:
  - "16.13.0"

services:
  - mongodb

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm test
  