---
os: linux
language: generic
dist: xenial
install:
- "./travis/install-reqs.sh"
script:
- "./travis/prepare-and-package.sh"
services:
- docker
before_install:
- for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd
  runc; do sudo apt-get remove $pkg; done
- sudo systemctl stop docker.service && sudo systemctl stop docker.socket
- sudo apt-get purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  docker-ce-rootless-extras
- sudo rm -rf /var/lib/docker
- sudo rm -rf /var/lib/containerd
- sudo apt-get update
- sudo apt-get install ca-certificates curl gnupg
- sudo install -m 0755 -d /etc/apt/keyrings
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o
  /etc/apt/keyrings/docker.gpg - sudo chmod a+r /etc/apt/keyrings/docker.gpg
- echo \ "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg]
  https://download.docker.com/linux/ubuntu \ $(. /etc/os-release && echo "$VERSION_CODENAME")
  stable" | \ sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- sudo apt-get update
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- yes | sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
if: type = pull_request and ((branch = prod and head_branch = main) or (branch = main))
after_success:
- "./travis/test-local.sh || travis_terminate 1"
