language: node_js
node_js:
  - "14" 

services:
  - mongodb

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@7.24.0 
  - sudo apt-get update
  - sudo apt-get install openssl

install:
  - npm install

script:
  - npm test
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in hello.txt.enc -out hello.txt -d
  - cat hello.txt



deploy:
  provider: script
  script: echo "Deploying to production..."
  on:
    tags: true