language: node_js
node_js:
  - "14" 

services:
  - mongodb

cache:
  directories:
    - node_modules

env:
  - ENV_VAR=foo
  - ENV_VAR=bar
  - ENV_VAR=baz


before_install:
  - npm install -g npm@7.24.0 
  - sudo apt-get update
  - sudo apt-get install openssl

install:
  - npm install

script:
  - npm test
  - echo "Running tests with ENV_VAR=$ENV_VAR"
  # - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in hello.txt.enc -out hello.txt -d
  # - cat hello.txt
  - node cowsay-nodejs/app.js



deploy:
  provider: script
  script: echo "Deploying to production..."
  on:
    tags: true